### ISSUE TITLE
Fatal error during login time

### ISSUE THREAD

**Issue by quantuumsnot** [litecart/litecart#297]
### What where you trying to do?
To login with admin credentials

### What actually happened?
Obviously the PHP spat a fatal error

### What did you expect to happen?
Obviously to login normally

### LiteCart Version

2.4.3

### PHP Version

7.4

### Error/Backtrace

```shell
Fatal error: Uncaught Error: Class 'IntlDateFormatter' not found in /home/xxx/shop.xxx.com/includes/library/lib_language.inc.php:303 Stack trace: #0 /home/xxx/shop.xxx.com/includes/library/lib_language.inc.php(418): language::{closure}(Object(DateTime), '%b') #1 [internal function]: language::{closure}(Array) #2 /home/xxx/shop.xxx.com/includes/library/lib_language.inc.php(420): preg_replace_callback('/(?<!%)(%[a-zA-...', Object(Closure), '%b') #3 /home/xxx/shop.xxx.com/admin123/graphs.widget/graphs.inc.php(34): language::strftime('%b', Object(DateTime)) #4 /home/xxx/shop.xxx.com/admin123/index.php(87): include('/home/whatsins/...') #5 {main} thrown in /home/xxx/shop.xxx.com/includes/library/lib_language.inc.php on line 303
```

### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

I don't know

### If this problem could be related to a browser. Which one?

Not relevant

**Comment by quantuumsnot** [comment]
Seems `intl` extension was not loaded, probably webhosting company disabled it by default after PHP is updated. Dunno why
